#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🔍 Vérification du linting..."
npm run lint

echo "🏗️  Vérification de la compilation..."
npm run build

echo "✅ Toutes les vérifications sont passées ! Vous pouvez pousser votre code."
